### ISSUE TITLE
Some Packet loss statistics are missing on ticket

### ISSUE THREAD

**Issue by Mahmo0odsalah** [oanguenot/webrtcmetrics#34]
In the readme[1], it lists that on ticket generation, the ticket includes these packet loss values: `avg`, `max`, `min`, `values`, `volatility`. However, when the ticket is generated all I can find is: `avg`, `values` and `lost`. 

I'm using v5.4.1.

[1]
![image](https://github.com/oanguenot/webrtcmetrics/assets/26148101/f95e8dbc-e1ad-4f12-8f50-72b92bb6b3f4)

**Comment by oanguenot** [comment]
This as been delivered in version 5.5.0

**Comment by Mahmo0odsalah** [comment]
Great news! Thank you @oanguenot
