### ISSUE TITLE
Handle unavailable MediaDevices

### ISSUE THREAD

**Issue by gondaruk** [oanguenot/webrtcmetrics#35]
First things first - thanks a lot for this library. It's awesome and works great.

I have met, though, a small issue when using it within non-secure context, for example, when page is opened using `http` (not https or localhost).

Outside of SecureContext mediaDevices property is [unavailable](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts):
> Navigator: mediaDevices property
> This feature is available only in [secure contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) (HTTPS), in some or all [supporting browsers](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/mediaDevices#browser_compatibility).

As a result, I get an error at [collector.js#L471](https://github.com/oanguenot/webrtcmetrics/blob/master/src/collector.js#L471):
> Cannot read properties of undefined (reading 'addEventListener')
> TypeError: Cannot read properties of undefined (reading 'addEventListener')

**Comment by oanguenot** [comment]
Hi Gondaruk,
Thanks for your feedback and PR, I will work on it shortly
